HW6 is completed
Karagar/Otus pull request #2
Opened 2020-09-22 14:04 UTC by Karagar

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-09-22 16:30 UTC, kulti requested changes
Либо я не понял идею, либо done не останавливает один стейдж, но при этом останавливает дополнительную горутину.

В остальном решение хорошее и понятное. Не хватает только оригинального теста.

2020-09-22 16:30 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("custom case", func(t *testing.T) {
В чем смысл этого теста? Из названия непонятно.

Он очень похож на done case и, по сути, ничего нового не проверяет.

2020-09-22 16:30 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		inputChan = checkDone(inputChan, done)
Мне кажется, что нужно оборачиваеть инпут для первого стейджа тоже. Сейчас получается, что done закроет инпуты для всех стейджей, начиная со второго.

2020-09-22 16:30 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	}()
Не уверен, что эта горутина нужна.

Если вместо pipe возвращать out последнего созданного stage, то результат будет тот же. done закроет инпуты для всех стейджей, которые в итоге закроют свои аутпуты.

2020-09-22 18:37 UTC, Karagar commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("custom case", func(t *testing.T) {
Смысл в проверке, что done-сигнал сработал не только для поступающих в дальнейшем, но и для уже прошедших часть обработок. Это наиболее осмысленный тест, пришедший в голову. Если есть другие предложения - я буду рад их реализовать)

2020-09-23 16:35 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("custom case", func(t *testing.T) {
Спасибо за пояснения. Теперь и по названию понятно, что проверяется.

Насчет других сценариев можно подумать в двух направлениях:
1. Граничные условия. Например, что будет, если список стейджей пустой?
2. Странные сценарии. Например, что будет, если в interface{} окажутся данные не того типа? Или что если один из стейджей зависнет? Какое поведение ожидается в этих случаях?

Это уже можно считать заданием со звездочкой :)

2020-09-23 16:35 UTC, kulti approved these changes
Теперь все здорово. ДЗ принято - 10/10.

2021-08-02 01:40 UTC, merged